# Generated by Django 5.0.6 on 2025-09-30 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField(help_text='Base64-encoded credential ID from WebAuthn', unique=True)),
                ('name', models.CharField(help_text="User-friendly name for this credential (e.g., 'MacBook Pro Touch ID')", max_length=100)),
                ('public_key', models.TextField(help_text='Base64-encoded public key')),
                ('sign_count', models.PositiveIntegerField(default=0, help_text='Signature counter to prevent replay attacks')),
                ('aaguid', models.CharField(blank=True, help_text='Authenticator Attestation GUID', max_length=100)),
                ('credential_type', models.CharField(default='public-key', help_text='Type of credential', max_length=50)),
                ('transports', models.JSONField(blank=True, default=list, help_text="Transport methods supported (e.g., ['usb', 'nfc', 'ble', 'internal'])")),
                ('device_type', models.CharField(blank=True, help_text='Type of authenticator device', max_length=50)),
                ('backup_eligible', models.BooleanField(default=False, help_text='Whether the credential is backup eligible')),
                ('backup_state', models.BooleanField(default=False, help_text='Whether the credential is currently backed up')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this credential is active and can be used')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this credential was used for authentication', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'ordering': ['-created_at'],
            },
        ),
    ]
