# Generated by Django 5.0.6 on 2025-09-30 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_webauthncredential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drill',
            options={'ordering': ['skill_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='drill',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='drill',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='drill',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='drill',
            name='title',
        ),
        migrations.RemoveField(
            model_name='drill',
            name='type',
        ),
        migrations.AddField(
            model_name='drill',
            name='cause',
            field=models.CharField(blank=True, choices=[('anxiety', 'Anxiety'), ('stress', 'Stress'), ('lack_of_confidence', 'Lack of Confidence'), ('poor_skills', 'Poor Skills')], help_text='Root cause this drill addresses (optional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='drill',
            name='description',
            field=models.TextField(default='', help_text='Detailed description of the drill'),
        ),
        migrations.AddField(
            model_name='drill',
            name='interactive_elements',
            field=models.JSONField(default=dict, help_text='Interactive elements configuration (e.g., timer_duration, prompts)'),
        ),
        migrations.AddField(
            model_name='drill',
            name='name',
            field=models.CharField(default='Untitled Drill', help_text='Name of the drill', max_length=100),
        ),
        migrations.AddField(
            model_name='drill',
            name='skill_type',
            field=models.CharField(choices=[('pronunciation', 'Pronunciation'), ('pacing', 'Pacing'), ('filler_words', 'Filler Words')], default='pronunciation', help_text='Type of skill this drill targets', max_length=20),
        ),
        migrations.CreateModel(
            name='DrillCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, help_text="User's self-rated score (0.0-10.0)", null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('notes', models.TextField(blank=True, help_text="User's notes about the drill session")),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Time spent on the drill in seconds', null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='coach.drill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'drill', 'completed_at')},
            },
        ),
    ]
