# Generated by Django 5.0.6 on 2025-11-03 05:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_alter_drill_options_remove_drill_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='cause',
            field=models.CharField(blank=True, choices=[('lexical', 'Lexical'), ('syntactic', 'Syntactic'), ('articulatory', 'Articulatory'), ('fluency', 'Fluency'), ('other', 'Other')], help_text='Predicted cause of speech issue', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='clarity_score',
            field=models.FloatField(blank=True, help_text='Clarity score from ensemble model (0.0-1.0, higher = worse clarity)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='filler_score',
            field=models.FloatField(blank=True, help_text='Filler score from ensemble model (0.0-1.0, higher = more fillers)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='pacing_score',
            field=models.FloatField(blank=True, help_text='Pacing score from ensemble model (0.0-1.0, higher = worse pacing)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recommended_drill',
            field=models.ForeignKey(blank=True, help_text='AI-recommended drill based on analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_feedbacks', to='coach.drill'),
        ),
    ]
