# Generated by Django 5.0.6 on 2025-11-22 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_feedback_cause_feedback_clarity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillcompletion',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Recorded audio file for this drill completion', null=True, upload_to='drill_recordings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='drillcompletion',
            name='difficulty_level',
            field=models.CharField(blank=True, help_text='Difficulty level used for this completion (beginner, intermediate, advanced)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='drillcompletion',
            name='drill_specific_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Drill-specific metrics (e.g., pronunciation_accuracy, pause_quality, rhythm_score)'),
        ),
        migrations.AddField(
            model_name='drillcompletion',
            name='ml_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed ML metrics: {fillers_count, filler_density, wpm, transcription, etc.}'),
        ),
        migrations.AddField(
            model_name='drillcompletion',
            name='ml_scores',
            field=models.JSONField(blank=True, default=dict, help_text='ML-based objective scores: {filler_score, clarity_score, pacing_score, overall_score}'),
        ),
        migrations.AlterField(
            model_name='drillcompletion',
            name='score',
            field=models.FloatField(blank=True, help_text="User's self-rated score (0.0-10.0) - deprecated, use ml_scores instead", null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
