# Generated by Django 5.0.6 on 2025-11-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_drillcompletion_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='reference_audio',
            field=models.FileField(blank=True, help_text='Reference audio file for pronunciation drills (optional)', null=True, upload_to='drill_reference_audio/%Y/%m/%d/'),
        ),
    ]
