# Generated by Django 5.0.6 on 2025-09-15 15:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the session was created')),
                ('duration', models.IntegerField(help_text='Duration of the speech session in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('filler_count', models.IntegerField(default=0, help_text="Number of filler words detected (e.g., 'um', 'uh', 'like')", validators=[django.core.validators.MinValueValidator(0)])),
                ('pacing_analysis', models.TextField(blank=True, help_text='Analysis of speaking pace and rhythm patterns')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('archived', 'Archived')], default='pending', help_text='Processing status of the speech session', max_length=20)),
                ('audio_file', models.FileField(blank=True, help_text='Original audio file for the speech session', null=True, upload_to='speech_sessions/%Y/%m/%d/')),
                ('transcription', models.TextField(blank=True, help_text='Transcribed text from the speech session')),
                ('confidence_score', models.FloatField(blank=True, help_text='Overall confidence score for the analysis (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this speech session', on_delete=django.db.models.deletion.CASCADE, related_name='speech_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speech Session',
                'verbose_name_plural': 'Speech Sessions',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='speech_sess_user_id_544ddd_idx'), models.Index(fields=['status'], name='speech_sess_status_c6cf52_idx'), models.Index(fields=['date'], name='speech_sess_date_7f8f42_idx')],
            },
        ),
    ]
