# Generated by Django 5.0.6 on 2025-11-22 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechsession',
            name='clarity_score',
            field=models.FloatField(blank=True, help_text='Clarity score from ML model (0.0-1.0, higher = worse clarity)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='filler_score',
            field=models.FloatField(blank=True, help_text='Filler score from ML model (0.0-1.0, higher = more fillers)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='speechsession',
            name='pacing_score',
            field=models.FloatField(blank=True, help_text='Pacing score from ML model (0.0-1.0, higher = worse pacing)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
