# Generated by Django 5.0.6 on 2025-11-28 06:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_sessions', '0002_speechsession_clarity_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedFiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler_word', models.CharField(help_text="The detected filler word (e.g., 'um', 'uh', 'like')", max_length=50)),
                ('word_position', models.IntegerField(help_text='Position of the filler word in the transcript (0-indexed)')),
                ('start_time', models.FloatField(blank=True, help_text='Start time of the filler word in seconds', null=True)),
                ('end_time', models.FloatField(blank=True, help_text='End time of the filler word in seconds', null=True)),
                ('context_before', models.CharField(blank=True, help_text='Words before the filler (for context)', max_length=100)),
                ('context_after', models.CharField(blank=True, help_text='Words after the filler (for context)', max_length=100)),
                ('detection_method', models.CharField(choices=[('spacy', 'spaCy NLP'), ('regex', 'Regex Pattern'), ('bert', 'BERT Model'), ('rule_based', 'Rule-based')], default='rule_based', help_text='Method used to detect this filler word', max_length=20)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score for this detection (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speech_session', models.ForeignKey(help_text='Speech session this filler was detected in', on_delete=django.db.models.deletion.CASCADE, related_name='detected_fillers', to='speech_sessions.speechsession')),
            ],
            options={
                'verbose_name': 'Detected Filler',
                'verbose_name_plural': 'Detected Fillers',
                'ordering': ['speech_session', 'word_position'],
                'indexes': [models.Index(fields=['speech_session', 'word_position'], name='speech_sess_speech__d6c319_idx'), models.Index(fields=['filler_word'], name='speech_sess_filler__0961b9_idx'), models.Index(fields=['detection_method'], name='speech_sess_detecti_27304e_idx')],
            },
        ),
    ]
